let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Casual Shirt",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img1: "images/img-1-1.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "Gradient Shirt",
    price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img1: "images/img-2-1.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "T-Shirt",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img1: "images/img-3-1.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Mens Suit",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img1: "images/img-4-1.jpg",
  },
  {
    id: "thiecbawdjksadjk",
    name: "Mens Tie",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img1: "images/img-5-1.jpg",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Casual shoes",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img1: "images/img-6-1.jpg",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "Black Suit",
    price: 450,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img1: "images/img-7-1.jpg",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "Polo Shirt",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img1: "images/img-8-1.jpg",
  },
  {
    id: "cbvxbcvsceldk",
    name: "Denim Shirt",
    price: 85,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img1: "images/img-9-1.jpg",
  },
  {
    id: "oiopijmjkhuihb",
    name: "Denim Pants",
    price: 120,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img1: "images/img-10-1.jpg",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "Basic Cap",
    price: 35,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img1: "images/img-11-1.jpg",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "Leather Boots",
    price: 350,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img1: "images/img-12-1.jpg",
  },
];
